### ISSUE TITLE
"java.lang.ClassCastException: com.google.gwt.core.client.JavaScriptObject$$EnhancerByMockitoWithCGLIB$$29edae7f cannot be cast to com.google.gwt.user.client.Element" while trying to test a widget extending SimpleLayoutPanel

### ISSUE THREAD

**Issue by konradstrack** [google/gwtmockito#4]
Let's take the following example:

``` java
public class MyPanel extends SimpleLayoutPanel {

    private Label label;

    public MyPanel() {
        label = GWT.create(Label.class);
        label.setText("It's my panel");

        add(label);
    }

}
```

And a test case:

``` java
@RunWith(GwtMockitoTestRunner.class)
public class MyPanelTests {

    private MyPanel myPanel;

    @Before
    public void setUp() {
        myPanel = new MyPanel();
    }

    @Test
    public void testTruth() {
        assertTrue(true);
    }
}
```

Running this test case will result in the following exception:

```
java.lang.ClassCastException: com.google.gwt.core.client.JavaScriptObject$$EnhancerByMockitoWithCGLIB$$bd5b9f31 cannot be cast to com.google.gwt.user.client.Element
    at com.google.gwt.user.client.DOM.createDiv(DOM.java:149)
    at com.google.gwt.user.client.ui.SimplePanel.<init>(SimplePanel.java:35)
    at com.google.gwt.user.client.ui.SimpleLayoutPanel.<init>(SimpleLayoutPanel.java:31)
    at cern.ais.plugin.gwt.client.layout.view.MyPanel.<init>(MyPanel.java:11)
    at cern.ais.plugin.gwt.client.layout.view.MyPanelTests.setUp(MyPanelTests.java:17)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at com.google.gwtmockito.GwtMockitoTestRunner.run(GwtMockitoTestRunner.java:102)
    at org.junit.runners.Suite.runChild(Suite.java:128)
    at org.junit.runners.Suite.runChild(Suite.java:24)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:77)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:195)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:63)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
```

If MyPanel extends Composite, everything works fine, but with SimpleLayoutPanel (or just SimplePanel) the result is the same as the one above.

Is this a known limitation?

In many cases widgets can be refactored to extend Composite, but is there a way of testing with gwtmockito those that have to extend something else than Composite, or is using GWTTestCase required in such cases?

**Comment by timeu** [comment]
Is there a known workaround for the `ClassCastException` that @kishorepalakollu  reported when dealing with `JavascriptObject` and `JsArray` ?

**Comment by kishore-palakollu** [comment]
@timeu  Actually i have created a mehtod to mock the  JavaScriptObject.createArray() and return the javascriptobject. and i mocked it .and after that i mocked the javascriptobjectobejct.cast and returned the jsarray. and this resolved my issue.

**Comment by vikram-github** [comment]
@ekuefler - I still get class cast exceptions in my code when I run GWT mockito test cases. Below is the snippet code which causing the cast issue.
Element testElement = (Element) Document.get().createElement(tag);

Caused by: java.lang.ClassCastException: com.google.gwt.dom.client.Element$$EnhancerByMockitoWithCGLIB$$4ba5b663 cannot be cast to com.google.gwt.user.client.Element.

Any workaround for this issue?

**Comment by kishore-palakollu** [comment]
@vikram-github  Yes even i faced the same issue,then i created two public methods in my class and 
did like this
Element testElement = getElement();
public documentReturntype getDoucment(){
return Document.get();
}
ou
public Element getElement(){
return getDocument().createElement(tag);
}

Now after this ,in your test file use spy Mocikto.spy() and mock the above two methods.
and return the respective return types when these methods are called.
This should work and it wont cause any impact in your application also.

**Comment by lynx-r** [comment]
``` java
@GwtMock Image mockImage;
Mockito.when(mockImage.getElement()).thenReturn(ImageElement.class);
```
@justinmk do you have a working example?

**Comment by khouari1** [comment]
Hey, I am experiencing the following class cast exception issue:

Caused by: java.lang.ClassCastException: com.google.gwt.dom.client.Text$$EnhancerByMockitoWithCGLIB$$4050ddf1 cannot be cast to com.google.gwt.dom.client.Element
	at org.gwtbootstrap3.client.ui.html.Text.<init>(Text.java:63)
	at org.gwtbootstrap3.client.ui.html.Text.<init>(Text.java:53)
	at org.gwtbootstrap3.client.ui.Heading.<init>(Heading.java:84)
	at org.gwtbootstrap3.client.ui.ModalHeader.<init>(ModalHeader.java:38)
	at org.gwtbootstrap3.client.ui.Modal.<init>(Modal.java:98)

**Comment by manstis** [comment]
@khouari1 Using ```@WithClassesToStub({ Text.class } )``` works in our cases.
