### ISSUE TITLE
cannot use com.google.gwt.user.datepicker.client.DatePicker

### ISSUE THREAD

**Issue by hnoerdli** [google/gwtmockito#55]
I am using gwtmockito 1.1.5

java.lang.ClassCastException: com.google.gwt.core.client.JavaScriptObject$$EnhancerByMockitoWithCGLIB$$c39d8300 cannot be cast to com.google.gwt.dom.client.Element
	at com.google.gwt.user.client.ui.HTMLTable$CellFormatter.getCellElement(HTMLTable.java:428)
	at com.google.gwt.user.client.ui.HTMLTable$CellFormatter.getRawElement(HTMLTable.java:441)
	at com.google.gwt.user.client.ui.HTMLTable$CellFormatter.access$400(HTMLTable.java:161)
	at com.google.gwt.user.client.ui.HTMLTable.cleanCell(HTMLTable.java:1578)
	at com.google.gwt.user.client.ui.HTMLTable.setText(HTMLTable.java:1175)
	at com.google.gwt.user.datepicker.client.DefaultCalendarView.setup(DefaultCalendarView.java:249)
	at com.google.gwt.user.datepicker.client.DatePicker.<init>(DatePicker.java:306)
	at com.google.gwt.user.datepicker.client.DatePicker.<init>(DatePicker.java:285)
	at com.kf.amplifire.modules.widgets.KfDatePickerCellTest.testImaMonkey(KfDatePickerCellTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at com.google.gwtmockito.GwtMockitoTestRunner.run(GwtMockitoTestRunner.java:301)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

My test class looks like this:
package com.a.bc.modules.widgets;

import static org.junit.Assert.assertTrue;

import org.junit.Test;
import org.junit.runner.RunWith;

import com.google.gwt.user.datepicker.client.DatePicker;
import com.google.gwtmockito.GwtMockitoTestRunner;

@RunWith(GwtMockitoTestRunner.class)
public class KfDatePickerCellTest {

   @Test
   public void testDatePicker() {

      DatePicker nosePicker = new DatePicker();
      assertTrue(nosePicker != null);
   }

}

**Comment by hnoerdli** [comment]
I just changed our code where we do:
 new DatePicker() 
to 
GWT.create(DatePicker.class) 
and now gwtmockito can return a mock and I do not get the same exception and I can now write unit tests.
