### ISSUE TITLE
#68 broke the build

### ISSUE THREAD

**Issue by cushon** [google/gwtmockito#70]
* In `GwtMockitoTest.java`, the import of `com.mls.web.client.core.ui.components.video.VideoCss` is unused and the class is not on the classpath.
* `GwtMockitoTest.shouldGenerateHashCodeForMessages` fails:

```
java.lang.StackOverflowError
	at com.google.gwtmockito.fakes.FakeMessagesProvider$1.invoke(FakeMessagesProvider.java:52)
	at com.google.gwtmockito.$Proxy27.hashCode(Unknown Source)
	at com.google.gwtmockito.fakes.FakeMessagesProvider$1.invoke(FakeMessagesProvider.java:55)
	at com.google.gwtmockito.$Proxy27.hashCode(Unknown Source)
	at com.google.gwtmockito.fakes.FakeMessagesProvider$1.invoke(FakeMessagesProvider.java:55)
	at com.google.gwtmockito.$Proxy27.hashCode(Unknown Source)
...
```

**Comment by cushon** [comment]
Fixed in 5cab7c21dc3dd36df06740693318ec9cb419e874.
